apiVersion: v1
kind: ServiceAccount
metadata:
  name: testuser
  namespace: proxysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-client
  namespace: proxysql
  labels:
    app: test-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-client
  template:
    metadata:
      labels:
        app: test-client
    spec:
      serviceAccountName: testuser
      containers:
      - name: client
        image: test-client
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
